spring.application.name=civ-monopoly-backend

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

server.tomcat.connection-timeout=-1

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000

logging.level.org.springframework.web.socket.messaging=DEBUG
logging.level.org.springframework.messaging=DEBUG

app.chat.public-chat-reference=${PUBLIC_CHAT_REFERENCE}